const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL: 'FETCH_COLLECTIONS_FAIL'
};

export default ShopActionTypes;
